# Setup
title:               Ajay George Blog
tagline:             'Blog about Code and Infrastructure'
description:         ' Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://ajaygeorge.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ajay George
  url:               https://twitter.com/ajaygeorge

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
